Repository puruagarwal1/Data-analysis, pull requests merged in 2024-10, with the labels that each got.

#2 Final
  DataScience.ipynb
Labels: good first issue, hacktoberfest accepted, hacktoberfest-accepted, hacktoberfest2024

#1 first
  numpy
Labels: hacktoberfest accepted, hacktoberfest-accepted, hacktoberfest2024

#3 Create second.py
  second.py
Labels: good first issue, hacktoberfest accepted, hacktoberfest-accepted, hacktoberfest2024

#5 Update and rename numpy to numpy.py
  numpy.py
Labels: hacktoberfest accepted, hacktoberfest-accepted, hacktoberfest2024

#7 Create third.py
  third.py
Labels: good first issue, hacktoberfest accepted, hacktoberfest-accepted, hacktoberfest2024

#8 Create fourth.py
  fourth.py
Labels: good first issue, hacktoberfest accepted, hacktoberfest-accepted, hacktoberfest2024

#9 IndoorObject Dectection
  IndoorObjectDetection.ipynb
Labels: hacktoberfest accepted, hacktoberfest-accepted, hacktoberfest2024

#10 Housing Data prediction
  HousingData.ipynb
Labels: enhancement, good first issue, hacktoberfest accepted, hacktoberfest-accepted, hacktoberfest2024
